### ISSUE TITLE
C1: Installing in non-english doesnt translate FF

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#43]

**Comment by star-buck** [comment]
not fixed. installing in German still has firefox esr in English.

**Comment by llelectronics** [comment]
The issue is it tries to download a package that isn't there anymore as calamares is not refreshing the package cache before trying to install the firefox locale package. 
Adding Adriaan here. 
Just as info. We are using Calamares 3.2.4 from Debian Buster repositories. Is there a way to force an "apt update" run to refresh the package cache in cala before it tries installing a new package?
